name: Snyk Test

on:
  pull_request:
    branches: [ "main" ]
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to build from
        default: main
        required: true

jobs:
  test_snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_name }}

      
      - name: Run Snyk to check for vulnerabilities
        id: snyk-scan-maven
        continue-on-error: true
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low

      - name: Build a Docker image
        run: docker build --file test.dockerfile -t test-img .
      
      - name: Run Snyk to check Docker image for vulnerabilities
        id: snyk-scan-docker
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: test-img
          args: --file=test.dockerfile
          # sarif: false
      
      - name: Upload result to GitHub Code Scanning
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Check docker image scan status
        if: ${{ steps.snyk-scan-docker.outcome == 'failure' }}
        run: exit 1